build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs"
  contactDetails:
    name: "Siti Zulaikha - Product Owner"
    email: "zulaikha.affandi@gmail.com"
  onCallSupport:
    -(555) 555-1234 ,
    -(555) 523-1345